### ISSUE TITLE
qBittorrent is not a constructor

### ISSUE THREAD

**Issue by bonny1992** [justmiles/node-qbittorrent-client#2]
I tried the example code but it gives me this errors.

Also, the example says to require 'qbtorrent-client', when the correct lib is 'qbittorrent-client', right?

**Comment by justmiles** [comment]
Thanks for pointing that out. I ran into some trouble trying to figure out how to best support the various API versions. I ended up exporting the class as three different versions: `API1`, `API2`, and `API3`.

As a result, instantiating the client would look like this:

``` coffee-script
qBittorrent  = require('qbittorrent-client').API3

client = new qBittorrent
    username: process.env.QBITTORRENT_USERNAME
    password: process.env.QBITTORRENT_PASSWORD
    host: process.env.QBITTORRENT_HOST
    port: process.env.QBITTORRENT_PORT
```
